import Body from './components/Body';
import Footer from './components/Footer';
import Header from './components/Header';
import './styles/home.css';

function Home() {
  const data = [
    {
      buyer: 'Albert Flores',
      buyer_color: 1,
      buyer_sub_color: 'rgba(236, 103, 103, 0.12)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '800',
      days: '3 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: '2 Days Ago',
      offer: '25'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 2,
      buyer_sub_color: 'rgba(167, 251, 238, 0.22)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '600',
      days: '2 Days',
      days_color: '#079E87',
      days_sub_color: 'rgba(167, 251, 238, 0.22)',
      post_day: 'Today',
      offer: '13'
    },
    {
      buyer: 'Robert Fox',
      buyer_color: 3,
      buyer_sub_color: 'rgba(208, 109, 255, 0.25)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '500',
      days: '1 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: '3 Days Ago',
      offer: '15'
    },
    {
      buyer: 'Jerome Bell',
      buyer_color: 4,
      buyer_sub_color: 'rgba(205, 230, 253, 0.75)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '4000',
      days: '8 Days',
      days_color: '#2440D6',
      days_sub_color: 'rgba(205, 230, 253, 0.75)',
      post_day: '1 Days Ago',
      offer: '37'
    },
    {
      buyer: 'Jacob Jones',
      buyer_color: 1,
      buyer_sub_color: 'rgba(236, 103, 103, 0.12)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '100',
      days: '4 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: 'Today',
      offer: '18'
    },
    {
      buyer: 'Wade Warren',
      buyer_color: 0,
      buyer_sub_color: 'rgba(237, 235, 177, 0.72)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '1200',
      days: '2 Days',
      days_color: '#D07D00',
      days_sub_color: 'rgba(200, 129, 22, 0.13)',
      post_day: '2 Days Ago',
      offer: '25'
    },
    {
      buyer: 'Arlene McCoy',
      buyer_color: 2,
      buyer_sub_color: 'rgba(167, 251, 238, 0.22)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '500',
      days: '5 Days',
      days_color: '#AC1D1D',
      days_sub_color: 'rgba(202, 95, 95, 0.13)',
      post_day: '1 Days Ago',
      offer: '32'
    },
    {
      buyer: 'Theresa Webb',
      buyer_color: 3,
      buyer_sub_color: 'rgba(198, 164, 255, 0.25)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '200',
      days: '2 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: 'Today',
      offer: '15'
    },
    {
      buyer: 'Arlene McCoy',
      buyer_color: 4,
      buyer_sub_color: 'rgba(205, 230, 253, 0.75)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '400',
      days: '2 Days',
      days_color: '#2440D6',
      days_sub_color: 'rgba(205, 230, 253, 0.75)',
      post_day: '1 Days Ago',
      offer: '50'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 1,
      buyer_sub_color: 'rgba(236, 103, 103, 0.12)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '800',
      days: '3 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: '2 Days Ago',
      offer: '25'
    },
    {
      buyer: 'Robert Fox',
      buyer_color: 2,
      buyer_sub_color: 'rgba(167, 251, 238, 0.22)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '600',
      days: '2 Days',
      days_color: '#079E87',
      days_sub_color: 'rgba(167, 251, 238, 0.22)',
      post_day: 'Today',
      offer: '13'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 3,
      buyer_sub_color: 'rgba(208, 109, 255, 0.25)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '500',
      days: '1 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: '3 Days Ago',
      offer: '15'
    },
    {
      buyer: 'Jerome Bell',
      buyer_color: 4,
      buyer_sub_color: 'rgba(205, 230, 253, 0.75)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '4000',
      days: '8 Days',
      days_color: '#2440D6',
      days_sub_color: 'rgba(205, 230, 253, 0.75)',
      post_day: '1 Days Ago',
      offer: '37'
    },
    {
      buyer: 'Arlene McCoy',
      buyer_color: 1,
      buyer_sub_color: 'rgba(236, 103, 103, 0.12)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '100',
      days: '4 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: 'Today',
      offer: '18'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 0,
      buyer_sub_color: 'rgba(237, 235, 177, 0.72)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '1200',
      days: '2 Days',
      days_color: '#D07D00',
      days_sub_color: 'rgba(200, 129, 22, 0.13)',
      post_day: '2 Days Ago',
      offer: '25'
    },
    {
      buyer: 'Jacob Jones',
      buyer_color: 2,
      buyer_sub_color: 'rgba(167, 251, 238, 0.22)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '500',
      days: '5 Days',
      days_color: '#AC1D1D',
      days_sub_color: 'rgba(202, 95, 95, 0.13)',
      post_day: '1 Days Ago',
      offer: '32'
    },
    {
      buyer: 'Arlene McCoy',
      buyer_color: 3,
      buyer_sub_color: 'rgba(198, 164, 255, 0.25)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '200',
      days: '2 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: 'Today',
      offer: '15'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 4,
      buyer_sub_color: 'rgba(205, 230, 253, 0.75)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '400',
      days: '2 Days',
      days_color: '#2440D6',
      days_sub_color: 'rgba(205, 230, 253, 0.75)',
      post_day: '1 Days Ago',
      offer: '50'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 1,
      buyer_sub_color: 'rgba(236, 103, 103, 0.12)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '800',
      days: '3 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: '2 Days Ago',
      offer: '25'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 2,
      buyer_sub_color: 'rgba(167, 251, 238, 0.22)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '600',
      days: '2 Days',
      days_color: '#079E87',
      days_sub_color: 'rgba(167, 251, 238, 0.22)',
      post_day: 'Today',
      offer: '13'
    },
    {
      buyer: 'Robert Fox',
      buyer_color: 3,
      buyer_sub_color: 'rgba(208, 109, 255, 0.25)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '500',
      days: '1 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: '3 Days Ago',
      offer: '15'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 4,
      buyer_sub_color: 'rgba(205, 230, 253, 0.75)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '4000',
      days: '8 Days',
      days_color: '#2440D6',
      days_sub_color: 'rgba(205, 230, 253, 0.75)',
      post_day: '1 Days Ago',
      offer: '37'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 1,
      buyer_sub_color: 'rgba(236, 103, 103, 0.12)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '100',
      days: '4 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: 'Today',
      offer: '18'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 0,
      buyer_sub_color: 'rgba(237, 235, 177, 0.72)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '1200',
      days: '2 Days',
      days_color: '#D07D00',
      days_sub_color: 'rgba(200, 129, 22, 0.13)',
      post_day: '2 Days Ago',
      offer: '25'
    },
    {
      buyer: 'Arlene McCoy',
      buyer_color: 2,
      buyer_sub_color: 'rgba(167, 251, 238, 0.22)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '500',
      days: '5 Days',
      days_color: '#AC1D1D',
      days_sub_color: 'rgba(202, 95, 95, 0.13)',
      post_day: '1 Days Ago',
      offer: '32'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 3,
      buyer_sub_color: 'rgba(198, 164, 255, 0.25)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '200',
      days: '2 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: 'Today',
      offer: '15'
    },
    {
      buyer: 'Wade Warren',
      buyer_color: 4,
      buyer_sub_color: 'rgba(205, 230, 253, 0.75)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '400',
      days: '2 Days',
      days_color: '#2440D6',
      days_sub_color: 'rgba(205, 230, 253, 0.75)',
      post_day: '1 Days Ago',
      offer: '50'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 1,
      buyer_sub_color: 'rgba(236, 103, 103, 0.12)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '800',
      days: '3 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: '2 Days Ago',
      offer: '25'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 2,
      buyer_sub_color: 'rgba(167, 251, 238, 0.22)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '600',
      days: '2 Days',
      days_color: '#079E87',
      days_sub_color: 'rgba(167, 251, 238, 0.22)',
      post_day: 'Today',
      offer: '13'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 3,
      buyer_sub_color: 'rgba(208, 109, 255, 0.25)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '500',
      days: '1 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: '3 Days Ago',
      offer: '15'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 4,
      buyer_sub_color: 'rgba(205, 230, 253, 0.75)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '4000',
      days: '8 Days',
      days_color: '#2440D6',
      days_sub_color: 'rgba(205, 230, 253, 0.75)',
      post_day: '1 Days Ago',
      offer: '37'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 1,
      buyer_sub_color: 'rgba(236, 103, 103, 0.12)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '100',
      days: '4 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: 'Today',
      offer: '18'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 0,
      buyer_sub_color: 'rgba(237, 235, 177, 0.72)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '1200',
      days: '2 Days',
      days_color: '#D07D00',
      days_sub_color: 'rgba(200, 129, 22, 0.13)',
      post_day: '2 Days Ago',
      offer: '25'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 2,
      buyer_sub_color: 'rgba(167, 251, 238, 0.22)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '500',
      days: '5 Days',
      days_color: '#AC1D1D',
      days_sub_color: 'rgba(202, 95, 95, 0.13)',
      post_day: '1 Days Ago',
      offer: '32'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 3,
      buyer_sub_color: 'rgba(198, 164, 255, 0.25)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '200',
      days: '2 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: 'Today',
      offer: '15'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 4,
      buyer_sub_color: 'rgba(205, 230, 253, 0.75)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '400',
      days: '2 Days',
      days_color: '#2440D6',
      days_sub_color: 'rgba(205, 230, 253, 0.75)',
      post_day: '1 Days Ago',
      offer: '50'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 1,
      buyer_sub_color: 'rgba(236, 103, 103, 0.12)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '800',
      days: '3 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: '2 Days Ago',
      offer: '25'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 2,
      buyer_sub_color: 'rgba(167, 251, 238, 0.22)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '600',
      days: '2 Days',
      days_color: '#079E87',
      days_sub_color: 'rgba(167, 251, 238, 0.22)',
      post_day: 'Today',
      offer: '13'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 3,
      buyer_sub_color: 'rgba(208, 109, 255, 0.25)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '500',
      days: '1 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: '3 Days Ago',
      offer: '15'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 4,
      buyer_sub_color: 'rgba(205, 230, 253, 0.75)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '4000',
      days: '8 Days',
      days_color: '#2440D6',
      days_sub_color: 'rgba(205, 230, 253, 0.75)',
      post_day: '1 Days Ago',
      offer: '37'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 1,
      buyer_sub_color: 'rgba(236, 103, 103, 0.12)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '100',
      days: '4 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: 'Today',
      offer: '18'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 0,
      buyer_sub_color: 'rgba(237, 235, 177, 0.72)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '1200',
      days: '2 Days',
      days_color: '#D07D00',
      days_sub_color: 'rgba(200, 129, 22, 0.13)',
      post_day: '2 Days Ago',
      offer: '25'
    },
    {
      buyer: 'Robert Fox',
      buyer_color: 2,
      buyer_sub_color: 'rgba(167, 251, 238, 0.22)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '500',
      days: '5 Days',
      days_color: '#AC1D1D',
      days_sub_color: 'rgba(202, 95, 95, 0.13)',
      post_day: '1 Days Ago',
      offer: '32'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 3,
      buyer_sub_color: 'rgba(198, 164, 255, 0.25)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '200',
      days: '2 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: 'Today',
      offer: '15'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 4,
      buyer_sub_color: 'rgba(205, 230, 253, 0.75)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '400',
      days: '2 Days',
      days_color: '#2440D6',
      days_sub_color: 'rgba(205, 230, 253, 0.75)',
      post_day: '1 Days Ago',
      offer: '50'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 1,
      buyer_sub_color: 'rgba(236, 103, 103, 0.12)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '800',
      days: '3 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: '2 Days Ago',
      offer: '25'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 2,
      buyer_sub_color: 'rgba(167, 251, 238, 0.22)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '600',
      days: '2 Days',
      days_color: '#079E87',
      days_sub_color: 'rgba(167, 251, 238, 0.22)',
      post_day: 'Today',
      offer: '13'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 3,
      buyer_sub_color: 'rgba(208, 109, 255, 0.25)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '500',
      days: '1 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: '3 Days Ago',
      offer: '15'
    },
    {
      buyer: 'Jerome Bell',
      buyer_color: 4,
      buyer_sub_color: 'rgba(205, 230, 253, 0.75)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '4000',
      days: '8 Days',
      days_color: '#2440D6',
      days_sub_color: 'rgba(205, 230, 253, 0.75)',
      post_day: '1 Days Ago',
      offer: '37'
    },
    {
      buyer: 'Wade Warrenr',
      buyer_color: 1,
      buyer_sub_color: 'rgba(236, 103, 103, 0.12)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '100',
      days: '4 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: 'Today',
      offer: '18'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 0,
      buyer_sub_color: 'rgba(237, 235, 177, 0.72)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '1200',
      days: '2 Days',
      days_color: '#D07D00',
      days_sub_color: 'rgba(200, 129, 22, 0.13)',
      post_day: '2 Days Ago',
      offer: '25'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 2,
      buyer_sub_color: 'rgba(167, 251, 238, 0.22)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '500',
      days: '5 Days',
      days_color: '#AC1D1D',
      days_sub_color: 'rgba(202, 95, 95, 0.13)',
      post_day: '1 Days Ago',
      offer: '32'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 3,
      buyer_sub_color: 'rgba(198, 164, 255, 0.25)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '200',
      days: '2 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: 'Today',
      offer: '15'
    },
    {
      buyer: 'Jerome Bell',
      buyer_color: 4,
      buyer_sub_color: 'rgba(205, 230, 253, 0.75)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '400',
      days: '2 Days',
      days_color: '#2440D6',
      days_sub_color: 'rgba(205, 230, 253, 0.75)',
      post_day: '1 Days Ago',
      offer: '50'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 1,
      buyer_sub_color: 'rgba(236, 103, 103, 0.12)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '800',
      days: '3 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: '2 Days Ago',
      offer: '25'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 2,
      buyer_sub_color: 'rgba(167, 251, 238, 0.22)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '600',
      days: '2 Days',
      days_color: '#079E87',
      days_sub_color: 'rgba(167, 251, 238, 0.22)',
      post_day: 'Today',
      offer: '13'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 3,
      buyer_sub_color: 'rgba(208, 109, 255, 0.25)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '500',
      days: '1 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: '3 Days Ago',
      offer: '15'
    },
    {
      buyer: 'Jacob Jones',
      buyer_color: 4,
      buyer_sub_color: 'rgba(205, 230, 253, 0.75)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '4000',
      days: '8 Days',
      days_color: '#2440D6',
      days_sub_color: 'rgba(205, 230, 253, 0.75)',
      post_day: '1 Days Ago',
      offer: '37'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 1,
      buyer_sub_color: 'rgba(236, 103, 103, 0.12)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '100',
      days: '4 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: 'Today',
      offer: '18'
    },
    {
      buyer: 'Jacob Jones',
      buyer_color: 0,
      buyer_sub_color: 'rgba(237, 235, 177, 0.72)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '1200',
      days: '2 Days',
      days_color: '#D07D00',
      days_sub_color: 'rgba(200, 129, 22, 0.13)',
      post_day: '2 Days Ago',
      offer: '25'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 2,
      buyer_sub_color: 'rgba(167, 251, 238, 0.22)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '500',
      days: '5 Days',
      days_color: '#AC1D1D',
      days_sub_color: 'rgba(202, 95, 95, 0.13)',
      post_day: '1 Days Ago',
      offer: '32'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 3,
      buyer_sub_color: 'rgba(198, 164, 255, 0.25)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '200',
      days: '2 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: 'Today',
      offer: '15'
    },
    {
      buyer: 'Jacob Jones',
      buyer_color: 4,
      buyer_sub_color: 'rgba(205, 230, 253, 0.75)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '400',
      days: '2 Days',
      days_color: '#2440D6',
      days_sub_color: 'rgba(205, 230, 253, 0.75)',
      post_day: '1 Days Ago',
      offer: '50'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 2,
      buyer_sub_color: 'rgba(167, 251, 238, 0.22)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '600',
      days: '2 Days',
      days_color: '#079E87',
      days_sub_color: 'rgba(167, 251, 238, 0.22)',
      post_day: 'Today',
      offer: '13'
    },
    {
      buyer: 'Jane Cooper',
      buyer_color: 3,
      buyer_sub_color: 'rgba(208, 109, 255, 0.25)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '500',
      days: '1 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: '3 Days Ago',
      offer: '15'
    },
    {
      buyer: 'Julio Gate',
      buyer_color: 4,
      buyer_sub_color: 'rgba(205, 230, 253, 0.75)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '4000',
      days: '8 Days',
      days_color: '#2440D6',
      days_sub_color: 'rgba(205, 230, 253, 0.75)',
      post_day: '1 Days Ago',
      offer: '37'
    },
    {
      buyer: 'Nanee Cooper',
      buyer_color: 1,
      buyer_sub_color: 'rgba(236, 103, 103, 0.12)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '100',
      days: '4 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: 'Today',
      offer: '18'
    },
    {
      buyer: 'Thuvr Cooper',
      buyer_color: 0,
      buyer_sub_color: 'rgba(237, 235, 177, 0.72)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '1200',
      days: '2 Days',
      days_color: '#D07D00',
      days_sub_color: 'rgba(200, 129, 22, 0.13)',
      post_day: '2 Days Ago',
      offer: '25'
    },
    {
      buyer: 'Arlene McCoy',
      buyer_color: 2,
      buyer_sub_color: 'rgba(167, 251, 238, 0.22)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '500',
      days: '5 Days',
      days_color: '#AC1D1D',
      days_sub_color: 'rgba(202, 95, 95, 0.13)',
      post_day: '1 Days Ago',
      offer: '32'
    },
    {
      buyer: 'David Cooper',
      buyer_color: 3,
      buyer_sub_color: 'rgba(198, 164, 255, 0.25)',
      desp: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '200',
      days: '2 Days',
      days_color: '#905DE6',
      days_sub_color: 'rgba(198, 164, 255, 0.25)',
      post_day: 'Today',
      offer: '15'
    }
  ];
  return (
    <div className="container">
      <Header />
      <Body data={data} />
      <Footer />
    </div>
  );
}

export default Home;
